# Generated by Django 3.1.3 on 2020-12-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201202_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
